### ISSUE TITLE
Help me! error: rpc error: code = Unimplemented desc = unknown service Anki.Vector.external_interface.ExternalInterface

### ISSUE THREAD

**Issue by khanhnguyen12345** [kercre123/wire-pod#147]
I got an error when VECTOR CONFIGURATION: " error: rpc error: code = Unimplemented desc = unknown service Anki.Vector.external_interface.ExternalInterface ". How to fix it? Thank Admin !

**Comment by khanhnguyen12345** [comment]
@kercre123 help me please. Thank You so much!!!

**Comment by Nanard421** [comment]
Hello, first thank you ! for creating wire-pod, my vector has re-birth.
 everything seems to work fine except in the Vector Configuration, i have the exact same message.

I'm running server on Windows WSL
Vector (prod version) was previously on firmware 0.9 and is now on 2.0.1 to run wire-pod

DDL servers seems down for months, so could this be the root cause ?
"Error pinging jdocs, likely unauthenticated" : what could that mean ? What is jdocs for ?

![Vector-01](https://github.com/kercre123/wire-pod/assets/128897808/8f350574-1dbe-4acb-8b81-826301f96eac)

![Vector-02](https://github.com/kercre123/wire-pod/assets/128897808/31e61bb1-431f-4194-a5af-73c21ed540fb)

**Comment by kercre123** [comment]
This is a common issue with WSL. I believe it's due to how requests are routed to the Linux VM. It's always best to run it on a native Linux machine, like a Raspberry Pi.

Wire-pod relies on being able to match serial numbers to IP addresses, and using that for identification. However, all requests to wire-pod are routed through the same virtualized network, so they aren't getting the same IP they would need in order to be able to communicate with the robot. So the robot is able to talk to it, but it can't talk to the robot.

Eventually, wire-pod will have a native Windows build which will solve this.

**Comment by Prolity** [comment]
I hated this error and fixed it on windows by installing ubuntu on a virtual machine (used VMware). Confirming it is related to wsl. Works 100% as intended

**Comment by Nuiana** [comment]
How did you get the VM to run as a bridged network? I can't get mine to do that.. and it can't find it when I do NAT - how did you solve this?

**Comment by Prolity** [comment]
Think it depends on vmware version, but bridged connection option was available for me. Maybe it helps to checks the steps on https://thesecmaster.com/install-ubuntu-linux-on-vmware-workstation/
