### ISSUE TITLE
Suggestions to make it work on MacOS

### ISSUE THREAD

**Issue by uandco** [kercre123/wire-pod#164]
Hi,

I managed to run wire-pod on MacOS with a few tweaks. It would be great to have them incorporated to the repo.

in `setup.sh`, I had to replace `/root` with `$HOME` in multiple places as there's no `/root` folder in MacOS, and you can't easily create a new folder in `/` in recent OSes.

As mentioned in the script itself, you need to install `brew`, `go` and the following `brew` packages:
```
brew install libopusenc
brew install libsodium
brew install opusfile
```

The latest `vosk-api`release doesn't contain precompiled darwin assets so you have to manually install https://github.com/alphacep/vosk-api/releases/download/v0.3.42/vosk-osx-0.3.42.zip which is the most recent osx asset.

Once downloaded, copy `vosk_api.h` to `~/.vosk/libvosk` (if you ran the setup from your user directory).
Copy `libvosk.dylib` to `/usr/local/lib`
Right click and choose "open" on `libvosk.dylib` to allow MacOS to allow the file to be open or it will fail when accessed later.

Failing to replace the header file and use the osx compiled lib will produce this error when running `sudo ./chipper/start.sh`:

```
ld: warning: ignoring file /Users/thibaut/.vosk/libvosk/libvosk.so, building for macOS-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x03 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 )
```

For some reason I also had to copy some files around to correct this issue:

```
ld: warning: directory not found for option '-L/Users/thibaut/go/pkg/mod/github.com/alphacep/vosk-api/go@v0.3.45/../src'
```

I copied the content of `go/pkg/mod/github.com/alphacep/vosk-api@v0.3.45` into `go/pkg/mod/github.com/alphacep/vosk-api` so it could find the `src` folder.

Last but not least, even when setting your computer name to `escapepod`, it will still complain it's incorrect as MacOS reports the name as `escapepod.local`:

```
WARNING: You have chosen the Escape Pod config, but the system hostname is not 'escapepod'. This means your robot will not be able to communicate with wire-pod unless you have a custom network configuration.
Actual reported hostname: escapepod.local
```

Ignore this, `escapepod.local` works fine.

I hope this helps others trying to run this on MacOS and some changes can be made to the scripts / wiki.

**Comment by lcxmas** [comment]
I am desperate.
so, please be patient.....and help me.
i did the following:

Installed :
https://github.com/alphacep/vosk-api/releases/download/v0.3.42/vosk-osx-0.3.42.zip w

copy vosk_api.h to ~/.vosk/libvosk (if you ran the setup from your user directory).
Copy libvosk.dylib to /usr/local/lib
Right click and choose "open" on libvosk.dylib to allow MacOS to allow the file to be open or it will fail when accessed later.

**I can't find   ~/.vosk/libvosk** 

i am stuck here

**Comment by lcxmas** [comment]
i have no idea where i could find this:
go/pkg/mod/github.com/alphacep/vosk-api@v0.3.45

**Comment by uandco** [comment]
@lcxmas the go folder would also be in your user directory if you started the setup from there, so ~/go/pkg/mod/github.com/alphacep/vosk-api@v0.3.45

**Comment by lcxmas** [comment]
Thanks for your explanation.
compiling is not my bread and butter but i am not totally a stranger to terminal and basic compiling.
having said that.
i really don't have:
~/go/pkg/mod/github.com/alphacep/vosk-api@v0.3.45
<img width="506" alt="Screen Shot 2023-08-15 at 8 15 14 AM" src="https://github.com/kercre123/wire-pod/assets/141543251/8bda3a83-4e61-42c1-9f6e-725040ac5864">


About this, ~/.vosk/libvosk .
in my .vosk there was no libvosk folder. i had to create one

**Comment by uandco** [comment]
That’s weird, looks like it’s not downloading the same packages as on my machine. 

A full output of both setup.sh and start.sh would help I guess.

**Comment by lcxmas** [comment]
Definitely struggling, now i am getting errors from nowhere.
i really need an official support!

**Comment by uandco** [comment]
@lcxmas try `brew install pkg-config` before running `start.sh`

**Comment by lcxmas** [comment]
doing again now!

**Comment by lcxmas** [comment]
i have got this error:

escapepod:wire-pod luca01$ sudo ./chipper/start.sh
# command-line-arguments
/usr/local/go/pkg/tool/darwin_amd64/link: running clang failed: exit status 1
ld: warning: ignoring file /Users/luca01/.vosk/libvosk/libvosk.so, building for macOS-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x03 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 )
Undefined symbols for architecture x86_64:
  "_vosk_gpu_init", referenced from:
      __cgo_b69c6a807b28_Cfunc_vosk_gpu_init in 000003.o
     (maybe you meant: __cgo_b69c6a807b28_Cfunc_vosk_gpu_init)
  "_vosk_gpu_thread_init", referenced from:
      __cgo_b69c6a807b28_Cfunc_vosk_gpu_thread_init in 000003.o
     (maybe you meant: __cgo_b69c6a807b28_Cfunc_vosk_gpu_thread_init)
  "_vosk_model_find_word", referenced from:
      __cgo_b69c6a807b28_Cfunc_vosk_model_find_word in 000003.o
     (maybe you meant: __cgo_b69c6a807b28_Cfunc_vosk_model_find_word, _github.com/alphacep/vosk-api/go._cgo_b69c6a807b28_Cfunc_vosk_model_find_word )
  "_vosk_model_free", referenced from:
      __cgo_b69c6a807b28_Cfunc_vosk_model_free in 000003.o
     (maybe you meant: _github.com/alphacep/vosk-api/go._cgo_b69c6a807b28_Cfunc_vosk_model_free, __cgo_b69c6a807b28_Cfunc_vosk_model_free )
  "_vosk_model_new", referenced from:
      __cgo_b69c6a807b28_Cfunc_vosk_model_new in 000003.o
     (maybe you meant: _github.com/alphacep/vosk-api/go._cgo_b69c6a807b28_Cfunc_vosk_model_new, __cgo_b69c6a807b28_Cfunc_vosk_model_new )
  "_vosk_recognizer_accept_waveform", referenced from:
      __cgo_b69c6a807b28_Cfunc_vosk_recognizer_accept_waveform in 000003.o
     (maybe you meant: __cgo_b69c6a807b28_Cfunc_vosk_recognizer_accept_waveform, _github.com/alphacep/vosk-api/go._cgo_b69c6a807b28_Cfunc_vosk_recognizer_accept_waveform )
  "_vosk_recognizer_final_result", referenced from:
      __cgo_b69c6a807b28_Cfunc_vosk_recognizer_final_result in 000003.o
     (maybe you meant: __cgo_b69c6a807b28_Cfunc_vosk_recognizer_final_result, _github.com/alphacep/vosk-api/go._cgo_b69c6a807b28_Cfunc_vosk_recognizer_final_result )
  "_vosk_recognizer_free", referenced from:
      __cgo_b69c6a807b28_Cfunc_vosk_recognizer_free in 000003.o
     (maybe you meant: __cgo_b69c6a807b28_Cfunc_vosk_recognizer_free, _github.com/alphacep/vosk-api/go._cgo_b69c6a807b28_Cfunc_vosk_recognizer_free )
  "_vosk_recognizer_new", referenced from:
      __cgo_b69c6a807b28_Cfunc_vosk_recognizer_new in 000003.o
     (maybe you meant: __cgo_b69c6a807b28_Cfunc_vosk_recognizer_new_grm, __cgo_b69c6a807b28_Cfunc_vosk_recognizer_new , _github.com/alphacep/vosk-api/go._cgo_b69c6a807b28_Cfunc_vosk_recognizer_new , __cgo_b69c6a807b28_Cfunc_vosk_recognizer_new_spk )
  "_vosk_recognizer_new_grm", referenced from:
      __cgo_b69c6a807b28_Cfunc_vosk_recognizer_new_grm in 000003.o
     (maybe you meant: __cgo_b69c6a807b28_Cfunc_vosk_recognizer_new_grm)
  "_vosk_recognizer_new_spk", referenced from:
      __cgo_b69c6a807b28_Cfunc_vosk_recognizer_new_spk in 000003.o
     (maybe you meant: __cgo_b69c6a807b28_Cfunc_vosk_recognizer_new_spk)
  "_vosk_recognizer_partial_result", referenced from:
      __cgo_b69c6a807b28_Cfunc_vosk_recognizer_partial_result in 000003.o
     (maybe you meant: __cgo_b69c6a807b28_Cfunc_vosk_recognizer_partial_result, _github.com/alphacep/vosk-api/go._cgo_b69c6a807b28_Cfunc_vosk_recognizer_partial_result )
  "_vosk_recognizer_reset", referenced from:
      __cgo_b69c6a807b28_Cfunc_vosk_recognizer_reset in 000003.o
     (maybe you meant: _github.com/alphacep/vosk-api/go._cgo_b69c6a807b28_Cfunc_vosk_recognizer_reset, __cgo_b69c6a807b28_Cfunc_vosk_recognizer_reset )
  "_vosk_recognizer_result", referenced from:
      __cgo_b69c6a807b28_Cfunc_vosk_recognizer_result in 000003.o
     (maybe you meant: __cgo_b69c6a807b28_Cfunc_vosk_recognizer_result, _github.com/alphacep/vosk-api/go._cgo_b69c6a807b28_Cfunc_vosk_recognizer_result )
  "_vosk_recognizer_set_max_alternatives", referenced from:
      __cgo_b69c6a807b28_Cfunc_vosk_recognizer_set_max_alternatives in 000003.o
     (maybe you meant: __cgo_b69c6a807b28_Cfunc_vosk_recognizer_set_max_alternatives, _github.com/alphacep/vosk-api/go._cgo_b69c6a807b28_Cfunc_vosk_recognizer_set_max_alternatives )
  "_vosk_recognizer_set_partial_words", referenced from:
      __cgo_b69c6a807b28_Cfunc_vosk_recognizer_set_partial_words in 000003.o
     (maybe you meant: __cgo_b69c6a807b28_Cfunc_vosk_recognizer_set_partial_words, _github.com/alphacep/vosk-api/go._cgo_b69c6a807b28_Cfunc_vosk_recognizer_set_partial_words )
  "_vosk_recognizer_set_spk_model", referenced from:
      __cgo_b69c6a807b28_Cfunc_vosk_recognizer_set_spk_model in 000003.o
     (maybe you meant: __cgo_b69c6a807b28_Cfunc_vosk_recognizer_set_spk_model, _github.com/alphacep/vosk-api/go._cgo_b69c6a807b28_Cfunc_vosk_recognizer_set_spk_model )
  "_vosk_recognizer_set_words", referenced from:
      __cgo_b69c6a807b28_Cfunc_vosk_recognizer_set_words in 000003.o
     (maybe you meant: _github.com/alphacep/vosk-api/go._cgo_b69c6a807b28_Cfunc_vosk_recognizer_set_words, __cgo_b69c6a807b28_Cfunc_vosk_recognizer_set_words )
  "_vosk_set_log_level", referenced from:
      __cgo_b69c6a807b28_Cfunc_vosk_set_log_level in 000003.o
     (maybe you meant: __cgo_b69c6a807b28_Cfunc_vosk_set_log_level, _github.com/alphacep/vosk-api/go._cgo_b69c6a807b28_Cfunc_vosk_set_log_level )
  "_vosk_spk_model_free", referenced from:
      __cgo_b69c6a807b28_Cfunc_vosk_spk_model_free in 000003.o
     (maybe you meant: _github.com/alphacep/vosk-api/go._cgo_b69c6a807b28_Cfunc_vosk_spk_model_free, __cgo_b69c6a807b28_Cfunc_vosk_spk_model_free )
  "_vosk_spk_model_new", referenced from:
      __cgo_b69c6a807b28_Cfunc_vosk_spk_model_new in 000003.o
     (maybe you meant: __cgo_b69c6a807b28_Cfunc_vosk_spk_model_new)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)





Chatgpt says:

This error message indicates that there are issues with linking your program. The necessary symbols for the functions defined in the `libvosk.so` library are not being found during the linking process. This could happen due to various reasons:

1. **Version or Architecture Mismatch:** The `libvosk.so` library might have been compiled for a different architecture than your system. For instance, if it was compiled for 32-bit and you're trying to link it in a 64-bit application, you could get this error.

2. **Incorrect Linking Options:** There might be an issue with the linking options specified in your project. Ensure that you've correctly specified the path to the library and that the linking options are accurate.

3. **Linking Order:** The order in which libraries are linked can be important. If the `libvosk.so` library depends on other libraries, ensure that they are linked in the correct order.

4. **Library Location:** Check that the path to the `libvosk.so` library is specified correctly and that the file is actually present in the specified location.

5. **Development Environment:** Make sure that the development environment is properly set up and that library paths are defined appropriately.

6. **Library Versions:** It could be that the version of `libvosk.so` is not compatible with your program's version. Ensure that library versions are consistent and compatible.

To resolve the issue, you might want to carefully check the linking options, ensure that the libraries have been compiled correctly for your architecture and OS version, and verify that the library path is correct. If the problem persists, you could seek further resources on the Vosk library support forum or consult development experts for additional assistance.


What do you think?

**Comment by uandco** [comment]
It means you didn’t replace libvosk.h and it’s trying to link the libvvosk.so lib instead of libvosk.dylib

**Comment by lcxmas** [comment]
replace libvosk.h with what and ...where?

**Comment by uandco** [comment]
From my original post:

Once downloaded, copy vosk_api.h to ~/.vosk/libvosk (if you ran the setup from your user directory).

**Comment by lcxmas** [comment]
i think i was able to fix this issue.

what about this error:

ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by uandco** [comment]
Not sure about that one, are you compiling on a Mac Silicon or Intel?

**Comment by lcxmas** [comment]
> Not sure about that one, are you compiling on a Mac Silicon or Intel?

Mac intel

**Comment by uandco** [comment]
I was also compiling on Mac Intel, this error should go away once you use the correct vosk header file and lib.
