### ISSUE TITLE
Can't setup vector with the escapepod firmware.

### ISSUE THREAD

**Issue by TheGithubJoshua** [kercre123/wire-pod#216]
On the update screen the progress bar never moves, I have waited hours any help?
![wpod](https://github.com/kercre123/wire-pod/assets/121495559/6740515e-44a1-4a60-a3c0-cf836505977d)

**Comment by seamonkey420** [comment]
just wanted to chime in since i was trying to get my wire-pod setup going today and yesterday.  i also was having major issues getting the escape pod firmware to download, mine would finally start downloading but after about 20 mins would stop and my vector would have a flashing ! on the screen. 

i then restarted my vector, put back into recovery mode, repaired and tried to download again. simiar issue after another 30 mins of waiting.  gave up for the night last night.  

today i decided to reset user data on my vector, then put back into recovery mode and paired to laptop. was able to finally get firmware downloaded but it did give me a ! twice so i had to restart but it seems like files continued from prev spot.  then tried to activate and had issues with not able to find server.  checked server, all services were running as they should be.  again put vector in recovery mode, repaired and went to firmware site and it downloaded again without any !s on the screen and went to activation mode. was finally able to activate and setup alexa.

so yea, i think somethings up on the firmware website. i'm actually amazed i got it up and running today with all the issues i had w/getting escape pod firmware on my vector.  thx to kercre123 and everyone for this.

**Comment by TheGithubJoshua** [comment]
Solved just by trying again using
[The epod setup page](https://keriganc.com/vector-epod-setup/html/main.html)
So definitely somethings up with that website @kercre123

**Comment by TheGithubJoshua** [comment]
Decided to reopen because this is still an issue with the setup page even though the epod setup page works fine.

**Comment by kercre123** [comment]
It works fine for me. vector-wirepod-setup and vector-epod-setup are exactly the same except they give Vector different OTAs. The only reason I can think of for this is maybe you went to the site before, when the OTA address pointed to a DDL server, and that cached. So maybe try CTRL+SHIFT+R. I will leave this open as I do need to create a better setup page which allows you to select the firmare you want.
