### ISSUE TITLE
From "wiki": "Every bot uses the same GUID for authentication..."

### ISSUE THREAD

**Issue by EchoInCloud** [kercre123/wire-pod#39]
wiki -> native Go Plugins ...
"
> Example plugin .go file:

> package main
> import "fmt"
> var Utterances = []string{"test plugin"}
> var Name = "Test Plugin"
>
> func Action(transcribedText string, botSerial string) string {
>    fmt.Println("(in testPlugin) Transcribed text: " + transcribedText ", serial number: " + botSerial)
>    return "intent_imperative_praise"
> }
> The plugin should be built with sudo /usr/local/go/bin/go build -buildmode=plugin plugin.go (has to be built with the same version of Go wire-pod is using and same user)
>
> The resulting .so should be placed in ~/wire-pod/chipper/plugins/. wire-pod will load it upon startup.
.> ... blablabla..
> Every bot uses the same GUID for authentication:
> tni1TRsTRTaNSapjo0Y+Sw==

"
WTF? Why ???
1. Node-red also performs this function much more easily with a serial number...
2. What is it that all vectors use the same GUID authentication? Is this meant to be a joke?

3.
> Weather commands are easy to setup via [weatherapi.com](https://github.com/kercre123/wire-pod/wiki/weatherapi.com) or > [openweathermap.org](https://github.com/kercre123/wire-pod/wiki/openweathermap.org)
> Knowledge-graph ("I have a question") commands are easy to setup via houndify

Node-Red without chipper same..

4.
> If you want to make wire-pod run in the background (as a daemon), run the following commands (press CTRL+C to stop wire-pod if you are running it):
> sudo ./setup.sh daemon-enable
> sudo systemctl start wire-pod

 ./setup.sh daemon-enable <-- ??? Really?  this is not  a typo?

**Comment by kercre123** [comment]
I couldn't figure out the relation between the client token and token hashes. If/when I figure that out, I will probably implement unique GUIDs for every authenticated bot. Otherwise, it shouldn't affect functionality and that is all that matters to me right now.

This is not a node-red alternative.

May you point out the typo to me? A more descriptive/accurate command would be `./setup.sh daemon-install` but it isn't very different
