### ISSUE TITLE
production vector re-authentication...

### ISSUE THREAD

**Issue by EchoInCloud** [kercre123/wire-pod#41]
The anki vectors have a protection "mechanism" that directly replaces the GUID.. if you eliminate this, it becomes manipulable and eavesdropping.. firewall programs do not protect against entities trained for this...

A better solution would be an automated re-authentication if the stored Vector name + certificate does not match the stored GUID.

The data of "home/$user/.anki_vector" should be used as a basis.. also a convenience aspect..

**Comment by kercre123** [comment]
This has been implemented, it will now read that ini file on startup and attempt to use the GUID from that in authentication before trying the global GUID.

Because we are missing a big part of the chain of security, wire-pod will never be as secure as the official servers. Every Vector has robot-specific keys, and from how I understand it, these are used in the process of generating a token for Vectors with the official servers. The official servers have access to the signing keys for each robot, we don't.
